### ISSUE TITLE
Does not exit gracefully if not a node project

### ISSUE THREAD

**Issue by iandotkelly** [iandotkelly/nlf#12]
/Users/ian/.nvm/v0.10.12/lib/node_modules/nlf/lib/module.js:29
		throw new Error('id must be defined');
		      ^
Error: id must be defined
    at new Module (/Users/ian/.nvm/v0.10.12/lib/node_modules/nlf/lib/module.js:29:9)
    at createModule (/Users/ian/.nvm/v0.10.12/lib/node_modules/nlf/lib/nlf.js:222:12)
    at parseModuleData (/Users/ian/.nvm/v0.10.12/lib/node_modules/nlf/lib/nlf.js:87:4)
    at parseInstalled (/Users/ian/.nvm/v0.10.12/lib/node_modules/nlf/lib/nlf.js:126:4)
    at /Users/ian/.nvm/v0.10.12/lib/node_modules/nlf/lib/nlf.js:346:3
    at /Users/ian/.nvm/v0.10.12/lib/node_modules/nlf/node_modules/read-installed/read-installed.js:119:5
    at /Users/ian/.nvm/v0.10.12/lib/node_modules/nlf/node_modules/read-installed/read-installed.js:233:14
    at asyncMap (/Users/ian/.nvm/v0.10.12/lib/node_modules/nlf/node_modules/read-installed/node_modules/slide/lib/async-map.js:27:18)
    at next (/Users/ian/.nvm/v0.10.12/lib/node_modules/nlf/node_modules/read-installed/read-installed.js:199:5)
    at /Users/ian/.nvm/v0.10.12/lib/node_modules/nlf/node_modules/read-installed/read-installed.js:156:7

**Comment by DanielSundberg** [comment]
I get the same error message in 1.3.0 (executed in Windows/Powershell):

C:\code\....\> nlf
C:\home\AppData\Roaming\npm\node_modules\nlf\lib\module.js:29
                throw new Error('id must be defined');
                      ^
Error: id must be defined
    at new Module (C:\home\AppData\Roaming\npm\node_modules\nlf\lib\module.js:29:9)
    at createModule (C:\home\AppData\Roaming\npm\node_modules\nlf\lib\nlf.js:299:12)
    at parseModuleData (C:\homen\AppData\Roaming\npm\node_modules\nlf\lib\nlf.js:91:4)
    at parseInstalled (C:\home\AppData\Roaming\npm\node_modules\nlf\lib\nlf.js:130:4)
    at C:\home\AppData\Roaming\npm\node_modules\nlf\lib\nlf.js:464:3
    at C:\home\AppData\Roaming\npm\node_modules\nlf\node_modules\read-installed\read-installed.js:138:5
    at C:\home\AppData\Roaming\npm\node_modules\nlf\node_modules\read-installed\read-installed.js:251:14
    at cb (C:\home\AppData\Roaming\npm\node_modules\nlf\node_modules\read-installed\node_modules\slide\lib\async-map.js:47:24)
    at C:\home\AppData\Roaming\npm\node_modules\nlf\node_modules\read-installed\read-installed.js:251:14
    at cb (C:\home\AppData\Roaming\npm\node_modules\nlf\node_modules\read-installed\node_modules\slide\lib\async-map.js:47:24)

My package.json:
{
  "author": "Removed",
  "name": "Removed",
  "repository": {
    "type": "git",
    "url": "git://github.com"
  },
  "dependencies": {
    "angular": "1.3.14",
    "bower": "1.4.1",
    "del": "1.1.1",
    "gulp": "3.8.11"
  },
  "devDependencies": {
    "coffee-script": "1.9.2",
    "event-stream": "3.2.2",
    "gulp-angular-templatecache": "1.5.0",
    "gulp-coffee": "2.3.1",
    "gulp-coffeelint": "0.4.0",
    "gulp-concat": "2.5.2",
    "gulp-inject": "1.2.0",
    "gulp-karma": "0.0.4",
    "gulp-less": "3.0.3",
    "gulp-minify-css": "0.5.1",
    "gulp-ng-annotate": "0.5.2",
    "gulp-plumber": "1.0.0",
    "gulp-streamify": "0.0.5",
    "gulp-uglify": "1.2.0",
    "gulp-util": "3.0.4",
    "gulp-webserver": "0.9.0",
    "http-server": "0.7.5",
    "jasmine-core": "2.2.0",
    "karma": "0.12.31",
    "karma-browserify": "4.0.0",
    "karma-chrome-launcher": "0.1.8",
    "karma-coffee-preprocessor": "0.2.1",
    "karma-coverage": "0.3.1",
    "karma-jasmine": "0.3.5",
    "karma-ng-html2js-preprocessor": "0.1.2",
    "karma-phantomjs-launcher": "0.1.4",
    "phantomjs": "1.9.16",
    "require-dir": "0.1.0",
    "stream-series": "0.1.1",
    "vinyl-source-stream": "1.0.0"
  }
}

**Comment by iandotkelly** [comment]
@DanielSundberg - thanks for the detailed report, I will try to replicate this on my pc.  I've not done any testing in powershell.

**Comment by iandotkelly** [comment]
@DanielSundberg - the good news is that I can replicate the issue on Win 8 powershell with that package.json.  Thanks.

**Comment by iandotkelly** [comment]
@DanielSundberg - the issue you have raised is unrelated to the original one.

It seems that this is cause by the fact that your top level package.json file does not have

- a "version" property, even a "0.0.0" is good
- a correct git url, even if the URL doesn't work e.g. git@github.com/test/test will work

It seems that without these, the read-installed module doesn't give nlf an ID.  Clearly nlf should be more tolerant than this, but you can fix your immediate issue by making those changes, deleting your node_modules folder and re-running npm install before running nlf again.

**Comment by DanielSundberg** [comment]
I can confirm that your workaround fixes the problem. Thank you for the effort!

**Comment by iandotkelly** [comment]
@DanielSundberg - excellent.  Thank you for raising the issue, I am sure many others have seen this issue and have stopped using it as a result. 

I will have to make it more tolerant of this .... perhaps by adding a "your-project@0.0.0" ID or similar if this happens.  I will release a version that does this at the weekend.

**Comment by iandotkelly** [comment]
@DanielSundberg - this should be fixed in https://github.com/iandotkelly/nlf/commit/f41cebf130f1faefe69803174c008026afb51d73 

I'll publish this as nlf@1.3.1

Thanks.

**Comment by DanielSundberg** [comment]
I can confirm that this is also fixed in the released version.
