### ISSUE TITLE
hangs forever

### ISSUE THREAD

**Issue by GeoffreyPlitt** [iandotkelly/nlf#17]
Running "nlf" just hangs forever for me. Also "npm test" gave me:

> nlf@0.2.9 test /vagrant/node_modules/nlf
> make

./node_modules/.bin/jshint \
		--verbose \
		index.js \
		test/unit/formatters/*.js \
		test/unit/*.js \
		lib/*.js \
		lib/formatters/*.js 
ERROR: Can't open test/unit/formatters/*.js
ERROR: Can't open test/unit/*.js
index.js: line 2, col 5, Bad line breaking before '?'. (W014)

I'm on precise64.

**Comment by iandotkelly** [comment]
@alexlawrence - in which case based on the 10:1 worst case I've seen, this may mean nlf takes 100 seconds to complete your project.  When you say 'hangs forever' can you leave it 5 minutes and see if it completes?

**Comment by iandotkelly** [comment]
@alexlawrence  - I found a significant factor to the performance, and I've improved it by a factor of 5-10, and released it as 1.2.0.  

I'm going to close this now but let me know if you find the performance is still a problem.

**Comment by alexlawrence** [comment]
@iandotkelly - that´s good news. Currently we are reconsidering which licenses we want to display. So for the moment we are not using nlf. However we may come back to it. Keep up the good work! I´m fine with closing the issue.
