### ISSUE TITLE
nlf.find() does not return duplicate module entries

### ISSUE THREAD

**Issue by amudukutore** [iandotkelly/nlf#19]
This is an enhancement request. It would be nice to provide an option that allows nlf.find() to return all entries for modules duplicated in the dependency hierarchy. For example, the module 'ms' can be found twince in the hierarchy of dependencies for express (under node_modules/debug/node_modules/ms
and node_modules/send/node_modules/ms) but nlf.find() only returns a single entry in its output array for 'ms'. Perhaps add a new boolean key to the options object ('getDuplicate') which would return these modules twice in the returned output array with module.directory set to the appropriate location.

**Comment by iandotkelly** [comment]
Now made obsolete by npm3
