### ISSUE TITLE
Add LICENSE file

### ISSUE THREAD

**Issue by edi9999** [iandotkelly/nlf#37]
It seems a bit ironic that a tool for finding out licenses doesn't have a license as a file in the repository (it is only in the package.json)

Can you please add one ?

**Comment by iandotkelly** [comment]
I could - but the license field in package.json is meant to be adequate.  It declares which SPDX license the module is licensed under.

**Comment by iandotkelly** [comment]
https://github.com/iandotkelly/nlf/commit/8f98b9b23b167866b3a6d7738f30449c70befb1f
