### ISSUE TITLE
[VULNERABILITY] Update to latest glob-all (depends on glob-all update)

### ISSUE THREAD

**Issue by shazron** [iandotkelly/nlf#40]
See:
https://github.com/jpillora/node-glob-all/issues/12

**Comment by iandotkelly** [comment]
Thanks - I'll take a look

**Comment by iandotkelly** [comment]
Its a potential denial of service - which isn't such a big deal for this application.  That said, I will update, test and release a patch for this.

**Comment by iandotkelly** [comment]
I've submitted a PR to node-glob-all fixing this vulnerability - i'm not dependent on him merging it or fixing it himself.  I'd rather not fork his solution at the moment.

**Comment by iandotkelly** [comment]
Fixed in https://github.com/iandotkelly/nlf/commit/24137c65df06154646abc6b368a6510eebb24386
