### ISSUE TITLE
Error when using nlf programatically

### ISSUE THREAD

**Issue by SMJ93** [iandotkelly/nlf#48]
I've run `npm install nlf --save`

Then I try to import it using import `import nlf from 'nlf';

I get loads of cannot resolve errors:

/node_modules/nlf/index.js
Module not found: Error: Can't resolve './lib-cov/nlf' in '/Users/user/Documents/product-web/node_modules/nlf'

Is there something i'm doing wrong?

**Comment by iandotkelly** [comment]
That's not finding the code coverage instrumented code used in testing only.  That shouldn't every be called unless you have 

```
NLF_COV=true
```

defined in your environment.  Can you give me some more details ... like operating system, node version etc?

**Comment by SMJ93** [comment]
Yeah, I was using it inside React with Babel.

Node: v8.1.0
NPM: 5.0.3
OS: Mac Sierra 10.12.6

I have decided to go with the command line option you provide and import the JSON. 

Great tool!!

**Comment by iandotkelly** [comment]
You could try using:

```
var nlf = require('nlf');
```

I'm not sure of your Babel setup, but all Babel does is convert `import` statements into equivalent `require` statements behind the scenes.   Its also the case that nlf isn't intended to run in the browser, so supporting ES6 modules isn't a priority.

I'm glad its working for you now.
