### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by IlCallo** [iandotkelly/nlf#50]
Some dependencies are really outdated and rise a warning when a package-lock containing them is loaded on GitHub. Is it possible to update them?

**Comment by iandotkelly** [comment]
Yeah - I'll do this today.

**Comment by iandotkelly** [comment]
Or at the very least in the next couple of days :)

**Comment by iandotkelly** [comment]
https://github.com/iandotkelly/nlf/releases/tag/2.0.1

**Comment by IlCallo** [comment]
![image](https://user-images.githubusercontent.com/10036108/35886729-534e51e4-0b92-11e8-960f-1e4793d17b64.png)
Problem seems to be still here :\
Seems to be given by node-tap and expect.js/mocha dependencies

**Comment by iandotkelly** [comment]
What tool are you using there to display known vulnerabilities?  You asked me to update dependencies, which I did to the latest at the time - short of stopping using those modules, I can't really do more.

Those modules (mocha and expect.js) are development dependencies only, and are not installed if you install using `npm i nlf`.

**Comment by IlCallo** [comment]
It's github which is complaining, when I load a package-lock.json which contains them.

I just required nlf as a normal dependency and run npm install, tomorrow I'll try removing node_modules folder and retrying the installation from zero

**Comment by iandotkelly** [comment]
Ok, this is a feature of github that I was not aware of.  I don't seem to have these modules or vulnerabilities when I look at the equivalent page:

https://github.com/iandotkelly/nlf/network/dependencies

**Comment by IlCallo** [comment]
Solved, it was another package messing it up, sorry

**Comment by iandotkelly** [comment]
Hey, no worries - I needed to update the dependencies anyway.
